set search_path=foliage2, public;

insert into FOLIAGE2.FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FOLIAGE2.FLGTIPO_ISTANZA_TAB TI
	join FOLIAGE2.FLGCIST_TAB I using (ID_CIST)
	cross join FOLIAGE2.FLGVINCOLI_TAB V
	cross join FOLIAGE2.FLGLIMITAZIONI_TAB L
where cod_tipo_istanza != 'SOTTO_SOGLIA'
	and COD_VINCOLO in ('AREE_PROTETTE', 'AREE_PAESAGGISTICHE')
	and COD_LIMITAZIONE = 'GENERICA_SOPRA_SOGLIA'
	and not exists (
			select *
			from FOLIAGE2.FLGVINCOLI_TIPO_ISTA_TAB VTI
			where VTI.ID_VINCOLO = V.ID_VINCOLO
				and VTI.ID_TIPO_ISTANZA = TI.ID_TIPO_ISTANZA
				and VTI.ID_LIMITAZIONE = L.ID_LIMITAZIONE
		);


