insert into FOLIAGE2.FLGCATEGORIE_REGIONI_TAB(ID_CATEGORIA, ID_REGIONE)
select id_categoria, id_regione
from FOLIAGE2.flgregi_viw fv
	cross join (
		select SPLIT_PART(T.line, '	', 1)::int as cod_categoria,
			SPLIT_PART(T.line, '	', 2) as nome,
			SPLIT_PART(T.line, '	', 3)='TRUE' as is_lazio,
			SPLIT_PART(T.line, '	', 4)='TRUE' as is_umbria
		from unnest(
				STRING_TO_ARRAY(
'1	BOSCHI DI LARICE E PINO CEMBRO	FALSE	FALSE
2	BOSCHI DI ABETE ROSSO	FALSE	FALSE
3	BOSCHI DI ABETE BIANCO	FALSE	FALSE
4	PINETE DI PINO SILVESTRE E PINO MONTANO	FALSE	FALSE
5	PINETE DI PINO NERO, PINO LARICIO E PINO LORICATO	TRUE	TRUE
6	PINETE DI PINI MEDITERRANEI	TRUE	TRUE
7	ALTRI BOSCHI DI CONIFERE PURE O MISTE	TRUE	TRUE
8	FAGGETE	TRUE	TRUE
9	QUERCETI A ROVERE, ROVERELLA E FARNIA	TRUE	TRUE
10	CERRETE, BOSCHI DI FARNETTO, FRAGNO E VALLONEA	TRUE	TRUE
11	CASTAGNETI	TRUE	TRUE
12	OSTRIETI, CARPINETI	TRUE	TRUE
13	BOSCHI IGROFILI	TRUE	TRUE
14	ALTRI BOSCHI CADUCIFOGLI	TRUE	TRUE
15	LECCETE	TRUE	TRUE
16	SUGHERETE	TRUE	TRUE
17	ALTRI BOSCHI DI LATIFOGLIE SEMPREVERDI	TRUE	TRUE
18	PIOPPETI ARTIFICIALI	FALSE	FALSE
19	PIANTAGIONI DI ALTRE LATIFOGLIE	FALSE	FALSE
20	PIANTAGIONI DI CONIFERE	FALSE	FALSE
21	ARBUSTETI SUBALPINI	FALSE	FALSE
22	ARBUSTETI A CLIMA TEMPERATO	FALSE	FALSE
23	MACCHIA, ARBUSTETI MEDITERRANEI	FALSE	FALSE',
'
'
				)
			) as T(line)
	) as T
	join FOLIAGE2.FLGCATEGORIE_TAB C using (cod_categoria)
where (regione = 'LAZIO' and is_lazio)
	or (regione = 'UMBRIA' and is_umbria);
