insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where COD_TIPO_ISTANZA_SPECIFICO = 'TAGLIO_BOSCHIVO'
	and COD_VINCOLO = 'NAT2K'
	and COD_LIMITAZIONE = 'NAT2K_4000MQ';

insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where COD_TIPO_ISTANZA_SPECIFICO = 'TAGLIO_BOSCHIVO'
	and COD_VINCOLO = 'HABITAT_PRIOR'
	and COD_LIMITAZIONE = 'HABITAT_VINCA_BOSCHIVO';

insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where COD_TIPO_ISTANZA_SPECIFICO = 'INTERVENTO_A_COMUNICAZIONE'
	and COD_VINCOLO = 'HABITAT_PRIOR'
	and COD_LIMITAZIONE = 'HABITAT_VINCA_COMUNICAZIONE';

insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where COD_TIPO_ISTANZA_SPECIFICO = 'TAGLIO_BOSCHIVO'
	and COD_VINCOLO = 'NAT2K'
	and COD_LIMITAZIONE = 'NAT2K_SOTTO_UMBRIA';

insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where COD_TIPO_ISTANZA_SPECIFICO = 'INTERVENTO_A_COMUNICAZIONE'
	and COD_VINCOLO = 'NAT2K'
	and COD_LIMITAZIONE = 'NAT2K_SOTTO_UMBRIA';

insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	join FLGCIST_TAB using (ID_CIST)
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where cod_tipo_istanza != 'SOTTO_SOGLIA'
	and COD_VINCOLO = 'NAT2K'
	and COD_LIMITAZIONE = 'NAT2K_SOPRA_SOGLIA_UMBRIA';


insert into FLGVINCOLI_TIPO_ISTA_TAB (ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE)
select ID_VINCOLO, ID_TIPO_ISTANZA, ID_LIMITAZIONE
from FLGTIPO_ISTANZA_TAB
	join FLGCIST_TAB using (ID_CIST)
	cross join FLGVINCOLI_TAB
	cross join FLGLIMITAZIONI_TAB
where cod_tipo_istanza != 'SOTTO_SOGLIA'
	and COD_VINCOLO in ('PAI_FRANE', 'PAI_VALANGHE', 'PAI_ALLUVIONI', 'AREE_PROTETTE')
	and COD_LIMITAZIONE = 'GENERICA_SOPRA_SOGLIA';
