server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors= always
server.error.include-exception=true

foliage.is_development=true

logging.level.org.springframework.security.web: INFO
logging.level.org.springframework.web = DEBUG

logging.level.it.almaviva.foliageMonitoraggio = DEBUG
#debug= true

logging.config=classpath:log4j2.dev.xml


foliage.backend.baseurl = http://127.0.0.1:8080/UmbriaBE/api/monitoraggio/
foliage.eop.preprocessing-url = http://10.206.228.168:8000
foliage.eop.monitoraggio-url = http://10.206.228.168:8001
foliage.cod-regione = 10

foliage.monitoraggio.shared-directory-local-path=C:\\foliage\\data
foliage.monitoraggio.shared-directory-container-path=/foliage/data
foliage.monitoraggio.path-dati-preelaborazione = preelaborazione.geojson


foliage.monitoraggio.skip-preprocessing=true
foliage.monitoraggio.skip-monitoring=true

foliage.monitoraggio.client-id = dev1
foliage.monitoraggio.backend-username = user
foliage.monitoraggio.backend-password = password

logging.level:debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: "trace"
logging.level.org.springframework.security.web.util.matcher.RegexRequestMatcher: "debug"

